// Copyright (C) 2026 HidayahTech, LLC
// Changelog modal — shows version history from the generated src/lib/changelog.js.
// CHANGELOG and CURRENT_VERSION are generated by build.mjs from CHANGELOG.md at build time.
// Do not edit src/lib/changelog.js directly.
import { useEffect, useState } from 'preact/hooks';
import { CHANGELOG, CURRENT_VERSION } from '../lib/changelog.js';

const RELEASES_URL  = 'https://gitlab.com/hidayahtech/bucketer/-/releases';
const RELEASES_API  = 'https://gitlab.com/api/v4/projects/hidayahtech%2Fbucketer/releases?per_page=1';
const BADGE_URL     = 'https://gitlab.com/hidayahtech/bucketer/-/badges/release.svg';

function semverGt(a, b) {
  const pa = a.split('.').map(Number);
  const pb = b.split('.').map(Number);
  for (let i = 0; i < 3; i++) {
    if (pa[i] > pb[i]) return true;
    if (pa[i] < pb[i]) return false;
  }
  return false;
}

// Persists across modal open/close within the same tab session.
let sessionCache = null; // { tag, version } | 'error'

export function ChangelogModal({ onClose }) {
  const [checkState, setCheckState] = useState(sessionCache ? 'done' : 'idle');
  const [checkResult, setCheckResult] = useState(sessionCache);

  useEffect(() => {
    const handler = (e) => { if (e.key === 'Escape') onClose(); };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, []);

  async function checkUpstream() {
    setCheckState('loading');
    try {
      const res = await fetch(RELEASES_API);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const [latest] = await res.json();
      const result = { tag: latest.tag_name, version: latest.tag_name.replace(/^v/, '') };
      sessionCache = result;
      setCheckResult(result);
      setCheckState('done');
    } catch {
      sessionCache = 'error';
      setCheckResult('error');
      setCheckState('error');
    }
  }

  const isNewer = checkResult && checkResult !== 'error' && semverGt(checkResult.version, CURRENT_VERSION);

  return (
    <div class="modal-overlay" onClick={onClose}>
      <div class="modal-dialog changelog-dialog" onClick={e => e.stopPropagation()}>
        <div class="modal-title">What's new in Bucketer</div>
        <div class="changelog-body">
          {CHANGELOG.map(entry => (
            <div key={entry.version} class="changelog-entry">
              <div class="changelog-version-row">
                <span class="changelog-version-num">v{entry.version}</span>
                <span class="changelog-version-date">{entry.date}</span>
                {entry.version === CURRENT_VERSION && (
                  <span class="changelog-current-badge">current</span>
                )}
              </div>
              {entry.title && <div class="changelog-entry-title">{entry.title}</div>}
              <ul class="changelog-changes">
                {entry.changes.map((c, i) =>
                  typeof c === 'string'
                    ? <li key={i}>{c}</li>
                    : (
                        <li key={i} class="changelog-group">
                          <span class="changelog-group-label">{c.group}</span>
                          <ul>{c.items.map((item, j) => <li key={j}>{item}</li>)}</ul>
                        </li>
                      )
                )}
              </ul>
            </div>
          ))}
        </div>
        <div class="changelog-upstream">
          {checkState === 'idle' && (
            <button class="btn btn-ghost btn-sm" onClick={checkUpstream}>Check for upstream release</button>
          )}
          {checkState === 'loading' && (
            <span class="upstream-status">Checking…</span>
          )}
          {checkState === 'done' && (
            <div class="upstream-result">
              <a href={`${RELEASES_URL}/${checkResult.tag}`} target="_blank" rel="noopener noreferrer">
                <img src={BADGE_URL} alt="Latest release" class="upstream-badge" />
              </a>
              {isNewer
                ? <span class="upstream-new">{checkResult.tag} available — <a href={`${RELEASES_URL}/${checkResult.tag}`} target="_blank" rel="noopener noreferrer">View release</a></span>
                : <span class="upstream-ok">You're up to date</span>}
            </div>
          )}
          {checkState === 'error' && (
            <span class="upstream-status upstream-err">Upstream check failed</span>
          )}
        </div>
        <div class="modal-actions">
          <button class="btn btn-ghost btn-sm" onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  );
}
